### ISSUE TITLE
Bloc state survival after configuration change

### ISSUE THREAD

**Issue by sebaslogen** [ptrbrynt/KotlinBloc#2]
Will the current state of a Bloc survive orientation changes?
I assume the examples with `remember` only survive recomposition but not configuration change (nor state restoration from process death)

Could you please provide an example of how to implement a Bloc for which the state (e.g. Loading) survives configuration changes (e.g. screen rotation)?

**Comment by ptrbrynt** [comment]
This is a great suggestion - thank you! I've now implemented a `rememberSaveableBloc` method which allows you to restore a Bloc after a configuration change:

```kotlin
rememberSaveableBloc(initialState = 0) { CounterBloc(it) }
```

Available in v0.17: https://github.com/ptrbrynt/KotlinBloc/releases/tag/0.17

Thank you again!
